version: '3'
services:
  guvi:
    # Use the image built by the Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
        # Container name
    container_name: guvi-app-container-prod
    # Map the container's port 80 to the host's port 3000 (or any port you prefer)
    ports:
      - "80:80"
    networks:
      - my-network

  express-server:
    build:
      context: ./express-server
    ports:
      - "3003:3003"
    networks:
      - my-network

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9102:9102"
    networks:
      - my-network

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9091"
    networks:
      - my-network
    depends_on:
      - express-server
      - node-exporter

  grafana:
    image: grafana/grafana
    ports:
      - "3004:3000"
    networks:
      - my-network
    depends_on:
      - prometheus
networks:
  my-network:
    driver: bridge

